### ISSUE TITLE
Typo in Branch: android-8.1 /init/init_oneplus3.cpp ?

### ISSUE THREAD

**Issue by mike1936** [moetayuko/android_device_oneplus_oneplus3#5]
https://github.com/dianlujitao/android_device_oneplus_oneplus3/blob/94923a16a6387eaced38cf4323987b43c9d23412/init/init_oneplus3.cpp#L52

Shoud be "OnePlus3T" instead?

**Comment by moetayuko** [comment]
not a typo, you can `getprop` in stock and check the returned value

**Comment by mike1936** [comment]
![default](https://user-images.githubusercontent.com/10584368/45286151-a14f3c80-b517-11e8-832f-1a80ab55da59.png)
The processor is MSM8996 Pro
Which is Snapdragon 821 according to this:
https://www.qualcomm.com/products/msm8996pro
returned value should be OnePlus3T I guess
as 3T has 821 while 3 has 820 CPU

**Comment by moetayuko** [comment]
`should be OnePlus3T I guess`
Don't guess, flash OxygenOS and `getprop`

**Comment by mike1936** [comment]
The value in the stock is OnePlus3 ... then there should be no problem.
THANKS A LOT !

I have one quick question, which is not related with this project:
Which key do we normally use to distinguish OnePlus3T from 3 ?
as I got stuck while flashing dual boot: the program wrongly recognize 3T as 3

**Comment by moetayuko** [comment]
idk, ask dualboot devs
